version: '3.8'
services:
  nest_service:
    build: .
    container_name: nest_service
    ports:
      - 3000:3333
    networks:
      - app-network
    volumes:
      - ./src/:/app/src/
      - .env/:/app/.env
    restart: always
    depends_on:
      - nest_database
    links:
      - nest_database
  nest_database:
    image: mongo:latest
    container_name: nest_database
    ports:
      - 27037:27017
    volumes:
      - dbdata:/data/db
    restart: always
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  dbdata:
