version: '3.8'
services:
  dev:
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    container_name: app_service
    ports:
      - 3033:3033
    networks:
      - app-network
    volumes:
      - ./src/:/app/src/
      - .env/:/app/.env
    restart: always
    depends_on:
      - app_database
  app_database:
    image: mongo:latest
    container_name: app_database
    ports:
      - 27027:27017
    volumes:
      - dbdata:/data/db
    restart: always
    networks:
      - app-network
  # app_test_database:
  #   image: mongo:latest
  #   container_name: app_test_database
  #   ports:
  #     - 27047:27017
  #   volumes:
  #     - dbdata:/test_data/test_db
  #   restart: always
  #   networks:
  #     - app-network
networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  dbdata:
