version: '3.8'
services:
  nest_service:
    build: .
    container_name: nest_service
    ports:
      - 3033:3033
    networks:
      - app-network
    volumes:
      - ./src/:/app/src/
      - .env/:/app/.env
    restart: always
    depends_on:
      - nest_database
    links:
      - nest_database
  nest_database:
    image: mongo:latest
    container_name: nest_database
    ports:
      - 27037:27017
    volumes:
      - dbdata:/data/db
    restart: always
    networks:
      - app-network
  test_nest_database:
    image: mongo:latest
    container_name: test_nest_database
    ports:
      - 27047:27017
    volumes:
      - dbdata:/test_data/test_db
    restart: always
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    driver: bridge
    # external: true
volumes:
  dbdata:
