version: '3'
services:
  nest:
    container_name: nest
    build: .
    ports:
      - '9001:9001'
    volumes:
      - .:/app
    links:
      - mongo_nest
  mongo_nest:
    image: mongo:latest
    container_name: mongo_nest
    ports:
      - '27020:27017'
    environment:
      MONGO_INITDB_DATABASE: nest
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
