version: '3.8'
services:
  app_dev:
    container_name: app_dev
    image: app-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: node dist/main
    ports:
      - 3033:3000
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - app_mongodb

  app_mongodb:
    image: mongo:latest
    container_name: app_mongodb
    networks:
      - app-network
    ports:
      - 27027:27017
    volumes:
      - app_dbdata:/data/db
    restart: always

volumes:
  app_dbdata:

networks:
  app-network:
    driver: bridge
